In [1]:
import numpy as np

In [2]:
a = (np.linspace(1,5))

In [3]:
a

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [4]:
a = (np.linspace(1,10,num=5,dtype="int"))

In [5]:
a

array([ 1,  3,  5,  7, 10])

In [6]:
a = (np.linspace([2,3],[4,6],num=3))

In [7]:
a

array([[2. , 3. ],
       [3. , 4.5],
       [4. , 6. ]])

In [8]:
a = (np.linspace(4,8,num=3))

In [9]:
a

array([4., 6., 8.])

In [10]:
b = (np.linspace(1,5,num=3,dtype="int"))

In [11]:
b

array([1, 3, 5])

In [12]:
c = (np.linspace(3,9,num=4,endpoint=False))

In [13]:
c

array([3. , 4.5, 6. , 7.5])

In [14]:
d = (np.linspace(4,8,num=3,retstep=True))

In [15]:
d

(array([4., 6., 8.]), 2.0)

In [16]:
a = (np.linspace(1,6,num=3,dtype="int"))

In [17]:
a

array([1, 3, 6])

In [18]:
y = (np.linspace(-5,5,7))

In [19]:
y

array([-5.        , -3.33333333, -1.66666667,  0.        ,  1.66666667,
        3.33333333,  5.        ])

In [20]:
b = (np.linspace(1,5,num=5,dtype="float"))

In [21]:
b

array([1., 2., 3., 4., 5.])